name: CI

on:
  push:
    branches: [ main, develop, 'chapter-*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          
      - name: Run tests
        run: |
          echo "Running basic tests..."
          python -m pytest tests/ -v
          
      - name: Test visual editor dependencies
        run: |
          echo "Checking visual editor dependencies..."
          cd visual
          npm ci
          npm run build
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            tests/
            visual/dist/ 